nginx:
   image: mthakkar/nginx
   ports:
    - "443:443"
   links:
    - myflask
   expose:
    - "443"
   tty: true
myflask:
   image: mthakkar/myflask
   ports: 
    - "5000:5000"
   links: 
    - mongohost
   expose:
    - "5000"
   tty: true
   container_name: myflask
mybart:
   image: mthakkar/mybartapp
   ports: 
    - "8090:8090"
   links: 
    - mongohost
   expose:
    - "8090"
   tty: true
   container_name: mybartapp
mongohost:
    image: mthakkar/mongo  
    container_name: mongohost
